CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE estado (
    "UF" character varying(3) NOT NULL,
    "Descricao" character varying(250) NOT NULL,
    CONSTRAINT "PK_estado" PRIMARY KEY ("UF")
);

CREATE TABLE cidade (
    "CodCidade" character varying(150) NOT NULL,
    "Descricao" character varying(500) NOT NULL,
    "estadoUF" character varying(3) NOT NULL,
    CONSTRAINT "PK_cidade" PRIMARY KEY ("CodCidade"),
    CONSTRAINT "FK_cidade_estado_estadoUF" FOREIGN KEY ("estadoUF") REFERENCES estado ("UF") ON DELETE CASCADE
);

CREATE TABLE bairro (
    "CodBairro" character varying(200) NOT NULL,
    "Descricao" character varying(500) NOT NULL,
    "cidadeCodCidade" character varying(150) NOT NULL,
    CONSTRAINT "PK_bairro" PRIMARY KEY ("CodBairro"),
    CONSTRAINT "FK_bairro_cidade_cidadeCodCidade" FOREIGN KEY ("cidadeCodCidade") REFERENCES cidade ("CodCidade") ON DELETE CASCADE
);

CREATE TABLE cliente (
    "CodCliente" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(300) NOT NULL,
    "CNPJ" text NOT NULL,
    "InscricaoMunicipal" character varying(150) NOT NULL,
    "RazaoSocial" character varying(250) NOT NULL,
    "CEP" character varying(20) NOT NULL,
    "Telefone" character varying(20) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Logradouro" text NOT NULL,
    "bairroCodBairro" character varying(200) NOT NULL,
    "cidadeCodCidade" character varying(150) NOT NULL,
    "estadoUF" character varying(3) NOT NULL,
    numero character varying(10) NOT NULL,
    CONSTRAINT "PK_cliente" PRIMARY KEY ("CodCliente"),
    CONSTRAINT "FK_cliente_bairro_bairroCodBairro" FOREIGN KEY ("bairroCodBairro") REFERENCES bairro ("CodBairro") ON DELETE CASCADE,
    CONSTRAINT "FK_cliente_cidade_cidadeCodCidade" FOREIGN KEY ("cidadeCodCidade") REFERENCES cidade ("CodCidade") ON DELETE CASCADE,
    CONSTRAINT "FK_cliente_estado_estadoUF" FOREIGN KEY ("estadoUF") REFERENCES estado ("UF") ON DELETE CASCADE
);

CREATE TABLE estabelecimento (
    "CodEstabelecimento" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeEstabelecimento" character varying(300) NOT NULL,
    "CNPJ" text NOT NULL,
    "InscricaoMunicipal" character varying(150) NOT NULL,
    "RazaoSocial" character varying(250) NOT NULL,
    "CEP" character varying(20) NOT NULL,
    "Telefone" character varying(20) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Logradouro" text NOT NULL,
    "bairroCodBairro" character varying(200) NOT NULL,
    "cidadeCodCidade" character varying(150) NOT NULL,
    "estadoUF" character varying(3) NOT NULL,
    numero text NOT NULL,
    CONSTRAINT "PK_estabelecimento" PRIMARY KEY ("CodEstabelecimento"),
    CONSTRAINT "FK_estabelecimento_bairro_bairroCodBairro" FOREIGN KEY ("bairroCodBairro") REFERENCES bairro ("CodBairro") ON DELETE CASCADE,
    CONSTRAINT "FK_estabelecimento_cidade_cidadeCodCidade" FOREIGN KEY ("cidadeCodCidade") REFERENCES cidade ("CodCidade") ON DELETE CASCADE,
    CONSTRAINT "FK_estabelecimento_estado_estadoUF" FOREIGN KEY ("estadoUF") REFERENCES estado ("UF") ON DELETE CASCADE
);

CREATE TABLE funcionario (
    "CodFuncionario" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(300) NOT NULL,
    "CNPJ" text NOT NULL,
    "InscricaoMunicipal" character varying(150) NOT NULL,
    "RazaoSocial" character varying(250) NOT NULL,
    "CEP" character varying(20) NOT NULL,
    "Telefone" character varying(20) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Logradouro" text NOT NULL,
    "bairroCodBairro" character varying(200) NOT NULL,
    "cidadeCodCidade" character varying(150) NOT NULL,
    "estadoUF" character varying(3) NOT NULL,
    numero text NOT NULL,
    CONSTRAINT "PK_funcionario" PRIMARY KEY ("CodFuncionario"),
    CONSTRAINT "FK_funcionario_bairro_bairroCodBairro" FOREIGN KEY ("bairroCodBairro") REFERENCES bairro ("CodBairro") ON DELETE CASCADE,
    CONSTRAINT "FK_funcionario_cidade_cidadeCodCidade" FOREIGN KEY ("cidadeCodCidade") REFERENCES cidade ("CodCidade") ON DELETE CASCADE,
    CONSTRAINT "FK_funcionario_estado_estadoUF" FOREIGN KEY ("estadoUF") REFERENCES estado ("UF") ON DELETE CASCADE
);

CREATE INDEX "IX_bairro_cidadeCodCidade" ON bairro ("cidadeCodCidade");

CREATE INDEX "IX_cidade_estadoUF" ON cidade ("estadoUF");

CREATE INDEX "IX_cliente_bairroCodBairro" ON cliente ("bairroCodBairro");

CREATE INDEX "IX_cliente_cidadeCodCidade" ON cliente ("cidadeCodCidade");

CREATE INDEX "IX_cliente_estadoUF" ON cliente ("estadoUF");

CREATE INDEX "IX_estabelecimento_bairroCodBairro" ON estabelecimento ("bairroCodBairro");

CREATE INDEX "IX_estabelecimento_cidadeCodCidade" ON estabelecimento ("cidadeCodCidade");

CREATE INDEX "IX_estabelecimento_estadoUF" ON estabelecimento ("estadoUF");

CREATE INDEX "IX_funcionario_bairroCodBairro" ON funcionario ("bairroCodBairro");

CREATE INDEX "IX_funcionario_cidadeCodCidade" ON funcionario ("cidadeCodCidade");

CREATE INDEX "IX_funcionario_estadoUF" ON funcionario ("estadoUF");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231114001538_estrutura_inicial', '7.0.13');

COMMIT;