// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gestorOficina.Data.Context;

#nullable disable

namespace Oficina.Dados.Migrations
{
    [DbContext(typeof(OficinaContext))]
    [Migration("20231107010920_alteracao_Estado")]
    partial class alteracao_Estado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Bairro", b =>
                {
                    b.Property<string>("CodBairro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CodCidade")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("cidadeCodCidade")
                        .HasColumnType("character varying(150)");

                    b.HasKey("CodBairro");

                    b.HasIndex("cidadeCodCidade");

                    b.ToTable("bairro");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Cidade", b =>
                {
                    b.Property<string>("CodCidade")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("estadoUF")
                        .HasColumnType("character varying(3)");

                    b.HasKey("CodCidade");

                    b.HasIndex("estadoUF");

                    b.ToTable("cidade");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodCliente"));

                    b.Property<string>("CEP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CodCliente");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Endereco", b =>
                {
                    b.Property<int>("CodCliente")
                        .HasColumnType("integer");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("bairroCodBairro")
                        .HasColumnType("character varying(200)");

                    b.Property<string>("cidadeCodCidade")
                        .HasColumnType("character varying(150)");

                    b.Property<string>("estadoUF")
                        .HasColumnType("character varying(3)");

                    b.HasKey("CodCliente");

                    b.HasIndex("bairroCodBairro");

                    b.HasIndex("cidadeCodCidade");

                    b.HasIndex("estadoUF");

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Estabelecimento", b =>
                {
                    b.Property<int>("CodEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodEstabelecimento"));

                    b.Property<string>("CEP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeEstabelecimento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("enderecoCodCliente")
                        .HasColumnType("integer");

                    b.HasKey("CodEstabelecimento");

                    b.HasIndex("enderecoCodCliente");

                    b.ToTable("estabelecimento");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Estado", b =>
                {
                    b.Property<string>("UF")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("UF");

                    b.ToTable("estado");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Funcionario", b =>
                {
                    b.Property<int>("CodFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodFuncionario"));

                    b.Property<string>("CEP")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("enderecoCodCliente")
                        .HasColumnType("integer");

                    b.HasKey("CodFuncionario");

                    b.HasIndex("enderecoCodCliente");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Bairro", b =>
                {
                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Cidade", "cidade")
                        .WithMany()
                        .HasForeignKey("cidadeCodCidade");

                    b.Navigation("cidade");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Cidade", b =>
                {
                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Estado", "estado")
                        .WithMany()
                        .HasForeignKey("estadoUF");

                    b.Navigation("estado");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Endereco", b =>
                {
                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Cliente", "cliente")
                        .WithOne("endereco")
                        .HasForeignKey("Oficina.Negocio.Modelo.Classes.Pessoa.Endereco", "CodCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Bairro", "bairro")
                        .WithMany()
                        .HasForeignKey("bairroCodBairro");

                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Cidade", "cidade")
                        .WithMany()
                        .HasForeignKey("cidadeCodCidade");

                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Estado", "estado")
                        .WithMany()
                        .HasForeignKey("estadoUF");

                    b.Navigation("bairro");

                    b.Navigation("cidade");

                    b.Navigation("cliente");

                    b.Navigation("estado");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Estabelecimento", b =>
                {
                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoCodCliente");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Funcionario", b =>
                {
                    b.HasOne("Oficina.Negocio.Modelo.Classes.Pessoa.Endereco", "endereco")
                        .WithMany()
                        .HasForeignKey("enderecoCodCliente");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("Oficina.Negocio.Modelo.Classes.Pessoa.Cliente", b =>
                {
                    b.Navigation("endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
